### ISSUE TITLE
Any .bin file as an example?

### ISSUE THREAD

**Issue by vitasam** [abelykh0/esp32-bkEmu#2]
Hello,
I was trying to load few .bin games from SD card (e.g. dizzy2021.bin, perestroika.bin), but nothing has been working.
Also it was not clear: should the BIN file be loaded (by pressing F3) straight from the BASIC screen or one should first go to MONITOR (MO ENTER) and press F3 there?

Could you include or at least provide a link/name to some of working binary file?

**Comment by abelykh0** [comment]
I placed some files in https://github.com/abelykh0/esp32-bkEmu/blob/main/test/F.zip. Unfortunately, I don't have time this week to test. I think "fish-demo.bin" was working.

**Comment by abelykh0** [comment]
By the way, look at this change: https://github.com/abelykh0/esp32-bkEmu/commit/a3d948686955a4b198cfcefef2dad2e1064fda23. Before it any file was crashing. I think something else needs to be done to support more files (clear registers?)

**Comment by vitasam** [comment]
Thanks, quite many programs from that .zip file work well. Regarding [a3d9486](https://github.com/abelykh0/esp32-bkEmu/commit/a3d948686955a4b198cfcefef2dad2e1064fda23) change - I'm afraid that I know very little about this architecture, just started to learn.
