### ISSUE TITLE
Вывод картинки-подсказки по F1

### ISSUE THREAD

**Issue by vitasam** [abelykh0/esp32-bkEmu#6]
Здравствуйте! А слишком сложно вывести картинку (размером с экран БК) с подсказкой раскладки кнопок клавиатуры БК на клавишах PC? 

Нажатие F1, к примеру

**Comment by abelykh0** [comment]
Можно сделать. Но нужно нарисовать картинку 512x256 черно-белую или 256х256 цветную (4х-цветную, можно выбрать любые 4 цвета). У меня есть похожая функция в Spectrum эмуляторе https://github.com/abelykh0/esp32-z80emu.

**Comment by vitasam** [comment]
Я попробую сделать два варианта подсказки тогда, если получится, выложу пулл-реквестом в /docs. Какой формат - .bmp?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abelykh0** [comment]
bmp подойдет, я переведу в биты.

**Comment by vitasam** [comment]
Добавил монохромный 512х256, для пробы. 
Кстати, может есть смысл большие бинарники (png, bmp) положить в GIT LFS?

**Comment by abelykh0** [comment]
OK, added in https://github.com/abelykh0/esp32-bkEmu/commit/b8003d4fc3c289d3f660f5e99cd44a8005a273c6. If you have time, please add more to it (see https://raw.githubusercontent.com/abelykh0/esp32-bkEmu/main/doc/flat_keyboard.png)

**Comment by vitasam** [comment]
Thanks, it looks just great! 
![20220201_182427](https://user-images.githubusercontent.com/5597505/152011773-9f32fd06-4db1-4407-8ff2-c4a3e66bd25b.jpg)

I will try to update the .BMP. Is there any ready-to-use tool to convert it into .h?

**Comment by abelykh0** [comment]
I used this one https://lvgl.io/tools/imageconverter
Color format: Indexed 2 colors
Options: Output in big-endian format

However, the colors are inverse.

There's probably more like this.

**Comment by vitasam** [comment]
Thanks! I will take a look

**Comment by vitasam** [comment]
There is something wrong with a bit order after converting the .BMP in to header file - the help screenshot is corrupted. So attaching the new .BMP here
[kbd_layout_1.zip](https://github.com/abelykh0/esp32-bkEmu/files/7990171/kbd_layout_1.zip)

**Comment by vitasam** [comment]
I just found quite useful script to convert BMP in to headers: https://github.com/robertgallup/python-bmp2hex
So, I managed to create a new help screen, new pull request is coming
